### PR TITLE
More improvements

### PR DESCRIPTION
**Pull request by perillo**
In this branch contains more minor improvements to ziglings.

These commits are not really necessary, excluding 34088c4.

### CODE REVIEW

**Comment by perillo** [comment]
@chrboesch Do you know why in https://github.com/ratfactor/ziglings/actions/runs/4788790782, on macos and windows the operation was canceled?

Also, do you think that in case of `zig fmt --check` error, `eowyn.sh` should print a simple error message?
Currently we have:
```
...
patches/healed/099_formatting.zig
Error: Process completed with exit code 1.
```

**Comment by chrboesch** [comment]
> on macos and windows the operation was canceled?

No.

> should print a simple error message?

What should it look like?

**Comment by perillo** [comment]
> > on macos and windows the operation was canceled?
> 
> No.
> 
> > should print a simple error message?
> 
> What should it look like?

Something like:
```sh
# Check the healed exercises formatting.
files=$(zig fmt --check patches/healed 2>&1)
zigret=$?

if [ $zigret -ne 0 ]
then
    printf "\nThe following files are not in canonical format:\n%s\n" "$files"
    exit 1
fi
```

The output is:
```
...
Healing 999_the_end...
patching file patches/healed/999_the_end.zig (read from exercises/999_the_end.zig)

The following files are not in canonical format:
patches/healed/099_formatting.zig
```

Not sure if this added complexity is really necessary.  The `-e` option should be disabled for it to work.

I will create another PR with only commits da3adea and 34088c4 from this PR, with some modifications.

**Comment by perillo** [comment]
Closed.  Replaced by #255 and a new PR

**Pull request closed without merging**
