### PR TITLE
Prevent error "cast discards const qualifier"

### PR DESCRIPTION
**Pull request by rofrol**

### CODE REVIEW

**Comment by ratfactor** [comment]
@rofrol Thanks! I was momentarily tempted to say that `printMe()` should instead define `self` as `Bar` rather than `*Bar` to fix this. But your fix is better because it keeps the usage consistent with what we're doing in the actual exercise. :+1:

**Comment by rofrol** [comment]
@ratfactor Is there a way to have this `printMe` working regardles if bar is var or const?

**Comment by rofrol** [comment]
This works `fn printMe(self: Bar)`

**Comment by ratfactor** [comment]
@rofrol Yes, exactly. If `printMe()` takes a `Bar` rather than `*Bar`, Zig knows that `self` will remain immutable and the value will remain const. Function parameters themselves are _always_ immutable, but in the case of pointers, the thing being _pointed to_ is mutable.

In fact, I'm glad you asked because yet another way to solve this is to have `printMe()` take a `*const Bar` parameter instead!

```
 pub fn printMe(self: *const Bar) void {
    ....
 }
```

In this case, `self` is immutable (the thing it points to cannot change) _and_ the Bar it's pointing to is _also_ immutable.  So the const property is no longer "lost" and the compiler is happy.

I believe I touch on this in a later exercise? But I'm glad this example will no longer cause any errors before we get to that because it can be really confusing.

**Pull request merged**
