### PR TITLE
Test nightly against zig unstable

### PR DESCRIPTION
**Pull request by mattnite**
had to make a couple minor changes to the bash scripts such as setting the shebang to bash since `[[` is used, and macos didn't have `realpath` for some reason, but it seems to work fine without

### CODE REVIEW

**Comment by ratfactor** [comment]
@mattnite Oooooh, this is really cool!  So what's really funny is that just _today_ I attempted to remove _some_ of the Bashisms:

https://github.com/ratfactor/ziglings/commit/71dd4ff1ae20dc54637198f9fa87c0fc27b33f55

And that's after @g-w1 helped push me that direction (unquestionably for the better):

https://github.com/ratfactor/ziglings/commit/54f9cfc0f0298a42473a109ee0f4eaf89710f153

I'd like to make this work on as many systems (well, with "shell") as possible and be simple/foolproof.  I'm tempted to say you just _have_ to run these two scripts from the `patches/` directory and remove the need for `realpath` as well?

I'm running out of daytime here, but I should be able to start taking a look at this tomorrow.

Thanks again! 😃

**Comment by g-w1** [comment]
`dirname $0` should work too :)

**Comment by ratfactor** [comment]
@g-w1 I tried that. When running Bash in POSIX-compatibility mode, `$0` is relative and `$(dirname $0)` gives me `.`. 😢 

@mattnite It looks like we can specify a `working-directory` https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun

So something like this?

```
defaults:
  run:
    shell: bash
    working-directory: ./patches
...
    - run: ./eowyn.sh
```

If that works, I'm gonna make a _much_ simpler check that `eowyn.sh` (and `gollum.sh`) runs from the correct directory (by simply checking that each script can see the other).

BTW: how do I test a GH workflow? I've never tried one before.

Thanks!

**Comment by ratfactor** [comment]
I've changed both test/patch scripts to be run from the project root dir, much simplifying everything, as it turns out. Crossing my fingers that this works...

**Comment by mattnite** [comment]
Awesome, Thanks for fixing that up!

**Comment by ratfactor** [comment]
@mattnite And it even works:

https://github.com/ratfactor/ziglings/runs/2100101116?check_suite_focus=true

I've never used GH workflows before. Zigling is wearing the big pants now!

💥  Thanks again! 💥

**Pull request merged**
