### PR TITLE
Memory allocation exercise

### LINKED ISSUE #193: Memory allocation example
As someone coming from Python, the most important difference with Zig is it's manual memory management. I would like to propose adding an example of memory allocation.

I think it could be introduced after `manypointers`?

For the example, how about getting a running average of an array and saving the result in a new array? We would have to pretend the input array is only known at run-time via user input, but would that be a reasonable conceit?

### PR DESCRIPTION
**Pull request by Seanny123**
A draft PR to discuss whether including memory allocation (which is part of the standard library, not the core language) is worth including in Ziglings.

Resolves #193

### CODE REVIEW

**Comment by vazub** [comment]
This topic is one of the cornerstones of efficient Zig usage and quite difficult to grok for people not accustomed to it, especially due to lacking tutorial resources. I would definitely suggest this is a must to include in ziglings.

**Comment by Seanny123** [comment]
@ratfactor before I make this MR pass the checks by adding patches, does this example seem reasonable to you? Are there some changes to the example text or framing that would improve it?

**Review by chrboesch — CHANGES_REQUESTED** [review]
```zig
var avg: []f64 = ???
```
Please add some question marks so that the user can see where to correct something.

**Comment by chrboesch** [comment]
> @chrboesch I changed the comment line length and put my example at the end

Looks very good! :smile:

**Comment by Seanny123** [comment]
Switched the empty placeholder to the `???` placeholder.

**Comment by ratfactor** [comment]
This looks great, thank you!

**Pull request merged**
