### PR TITLE
build: enable full parallelism when -Dhealed is set

### PR DESCRIPTION
**Pull request by perillo**
In this branch I plan to push more improvements to `build.zig`.

  - [x] Make the `eowyn` workflow go faster
  - [x] #229
  - [x] Add support for skipping disabled exercises
  - [x] Add tests
  - [x] #227

### CODE REVIEW

**Comment by perillo** [comment]
Enabling full parallelism, the build time on on github improved by 50% (from 2m to 1m on ubuntu-latest).

**Comment by perillo** [comment]
The next commit should be the last.

**Comment by perillo** [comment]
@chrboesch, I was planning to add new commit, rewriting `ZiglingStep` in order to use the standard build step, but it was harder than I thought.

You can merge this branch, if you think all is good.

Thanks.

**Comment by chrboesch** [comment]
Thank you so much! :smile:

**Pull request merged**
