### PR TITLE
add nix-shell

### PR DESCRIPTION
**Pull request by happysalada**
Hi,
   I don't know if you are open to it, but this is a simple nix-shell so that people with nix don't need to do anything to use your repo.
    I'm open if you need/want more info.
Let me know if I can do anything,
Raphael

### CODE REVIEW

**Comment by ratfactor** [comment]
Hi @happysalada, thanks for the PR!  Nix is getting really popular and I imagine people would enjoy this.

On the other hand, I'm super hesitant to add too many files to the root of the directory. I'd like to keep that as clean as absolutely possible.  One of the beauties of using the Zig build system is that Ziglings works in any environment where Zig works out-of-the-box.

Is there _any_ way this could be made to work from another directory like `extras/` or similar?

**Comment by happysalada** [comment]
the envrc file is to make it work with direnv, it's a program that allows you to get a nix shell as soon as you cd into the directory. It is not necessary per say, it just makes everything really convenient. My thought was that, with this, you don't need a readme for a lot of people. As soon as they cd in the directory they have the tools needed. However that file is not needed per say. You could add an instruction in the readme of how to run a shell (basically say that they have go `nix-shell` when they are inside the main directory). 
So there is a possibility to remove this file, but if you use this file, as far as I know, it has to be in the root.

Regarding nix, from what I know, there needs to be at least one file .nix in the root of the project, it can reference other files inside directories, there needs to be at least one .nix file.

Let me know if that answers your questions

**Comment by ratfactor** [comment]
@happysalada Just wanted to let you know that I've been inspired to try out Nix myself to see how this works. So I'm not ignoring this PR - in fact, quite the opposite. :-)

**Comment by happysalada** [comment]
Great!
I don't know what machine you are using, but zig is broken for mac right now.
So in this shell, I just download the binary for macOS (I'm on a mac).
No rush at all. Let me know if you need any changes.

**Comment by bnjmnt4n** [comment]
Given that ziglings requires zig 0.8.0-dev, maybe this PR should completely avoid nixpkgs' zig package (which is still at 0.7.1) and just download (pinned?) binaries for Linux as well?

**Comment by happysalada** [comment]
You're right of course. Pushed a fix.
Note that this could be further improved by checking on whether it is Arm or not, but I think it will do for now.

**Comment by ratfactor** [comment]
@happysalada Sadly, I'm going to decline this for now.

Pros:
1. Would be handy for Nix users

Cons:
1. Would be more stuff in the root dir
2. Wouldn't be "fair" for users of other systems
3. Would need to be maintained - and I won't be doing that

Number 3 is the big con that I'm stuck on.  I've tried out Nix and it's really great, but I'm not using it yet, so I won't be maintaining this file and I'm afraid it will become a point of frustration if it doesn't work as expected.

Thank you again for submitting this. I'll remember it exists and perhaps someday in the future it will find its way into Ziglings.

**Comment by happysalada** [comment]
No worries!
Thank you for having a look at it!

**Pull request closed without merging**
