### PR TITLE
Added testing exercise.

### PR DESCRIPTION
**Pull request by chrboesch**
closes https://github.com/ratfactor/ziglings/issues/277

### CODE REVIEW

**Comment by chrboesch** [comment]
@perillo What does this error means: 
```
   +- RemoveDir /home/runner/work/ziglings/ziglings/zig-cache/tmp/cedb2d3eea8bc44c transitive failure
   |  +- check failure
   |     +- zig build -Dhealed success 1m MaxRSS:168M
   |        +- heal success
   |           +- case-2 cached
```

**Comment by chrboesch** [comment]
There is another hint:
`check: error: 999_the_end.zig: expected to see "Compiling 999_the_end.zig...", found "PASSED:"`

**Comment by chrboesch** [comment]
After the third run I get other errors:
`zig build -Dhealed -Dn=94: error: the following command exited with code 2 (expected exited with code 0):`

Weird.

**Comment by chrboesch** [comment]
Maybe it depends on https://github.com/ratfactor/ziglings/pull/300

**Comment by perillo** [comment]
> There is another hint: `check: error: 999_the_end.zig: expected to see "Compiling 999_the_end.zig...", found "PASSED:"`

The cause is the new exercise 102, that confuses the CheckStep.
The solution is to update the tests.

**Comment by perillo** [comment]
> After the third run I get other errors: `zig build -Dhealed -Dn=94: error: the following command exited with code 2 (expected exited with code 0):`
> 
> Weird.

I can not reproduce it.  Can you tell me the error message?

**Comment by chrboesch** [comment]
Just run `zig build test` or take a look at: https://github.com/ratfactor/ziglings/actions/runs/4974676427/jobs/8901548287#step:4:15

**Comment by chrboesch** [comment]
> The solution is to update the tests.

I already updated the tests. But as you can see in the github actions, there is no error on 102: https://github.com/ratfactor/ziglings/actions/runs/4974676427/jobs/8901548287#step:4:325

**Comment by perillo** [comment]
@chrboesch I have fixed the problem. I will create a PR later (with some changes in how testing is implemented)

**Comment by chrboesch** [comment]
> I will create a PR later

ok

**Pull request merged**
