### PR TITLE
Refactor ZiglingStep more

### PR DESCRIPTION
**Pull request by perillo**
- [x] Remove the `is_testing` field (I forgot to remove it in #305)
  - [x] Remove the `eval` method, and use `std.Build.Step.evalZigProcess` instead.
         Also remove `src/ipc.zig`.
         This greatly simplifies the code!
  - [x] Use `std.Build.Step.fail` to report error messages.
         Now error handling is done in only one place: `printError`.

## WARNING

I removed coloring of error messages.  Coloring is now done in `printError`, where only the `"error: "` string is in red.
This is the style used in the Zig Build system.

Let me know if you prefer the old coloring.

### CODE REVIEW

**Comment by perillo** [comment]
Here is a script that reproduces some error with the new style:
https://gist.github.com/perillo/40d52c92169b3a1304963de6806f3563

**Comment by chrboesch** [comment]
>Let me know if you prefer the old coloring.

When I see this in just the terminal color (no more red) then I think it's not the best choice:

```
========= expected this output: ==========
Hello world!
========= but found: =====================
this is a test
==========================================
```
:thinking:

**Comment by chrboesch** [comment]
Made some tests and compare old vs. new and think, I prefer the old coloring.

**Comment by perillo** [comment]
> Made some tests and compare old vs. new and think, I prefer the old coloring.

Ok.

I will try with the following style:
  - The `"error: "` string will be in bold red (the one used by the Zig compiler)
  - The error message will be in faint red (using the same *formatting* as the old one)

**Comment by perillo** [comment]
@chrboesch : Let me know if the new coloring is ok.

**Comment by chrboesch** [comment]
> Let me know if the new coloring is ok.

It's ok now.

**Comment by perillo** [comment]
> > Let me know if the new coloring is ok.
> 
> It's ok now. Update: It seems Zig uses "bright red". When you write `\x1b[1;31m` it looks similar. Update2: Colors are the same but they print bold. That's the difference.

`1` means "Bold or increased intensity" and 2 means "Faint, decreased intensity, or dim".
The colors in `std.debug.TTY.Config` always set bold: https://github.com/ziglang/zig/blob/master/lib/std/debug.zig#L678.

**Comment by ratfactor** [comment]
zigred

I'm not _hugely_ bothered by the three different red styles...my only concern is that the non-bold red "expected this" and "but found" messages are actually **hard to read** depending on your screen and/or the light in the room, etc.

**Comment by perillo** [comment]
> zigred
> 
> I'm not _hugely_ bothered by the three different red styles...my only concern is that the non-bold red "expected this" and "but found" messages are actually **hard to read** depending on your screen and/or the light in the room, etc.

Probably it was a mistake the use of dim red.  Using the normal red (as it was done before) should fix it.

Alternatives are:
  1. Use Zig build runner style (only the `"error: "` string is in bold red, and the error message is in the default color/font-weight - white on a Linux terminal)
  2. Apply bold to the error message, as it is done by the Zig compiler for the error message and source file path

**Comment by chrboesch** [comment]
For me worked `\x1b[1;31m` as I mentioned before:

colors

**Comment by perillo** [comment]
A recent commit ziglang/zig@5d3f3ca removed setting `bold` to colors.

**Comment by chrboesch** [comment]
> A recent commit...

Thanks, we should consider that.

**Comment by perillo** [comment]
No updates?

**Pull request merged**
