### PR TITLE
build: fix build for latest zig version

### PR DESCRIPTION
**Pull request by sterchelen**
Currently, you can't build ziglings from zig's master branch (at the time of writing, https://github.com/ziglang/zig/commit/c31007bb47a4d1d62917324a33e9a9a6cd1df5a6 is master's HEAD) 
This patch set adapts ziglings' build code to reflect the changes on latest zig version.   

---
A large and impactful change was made on zig's build facilities. The following PR https://github.com/ziglang/zig/pull/14647 introduced those changes.

To be more precise, here are the impacts
* the color handling on tty
* the removal of the LogStep logic

### CODE REVIEW

**Comment by chrboesch** [comment]
Thank you for this hint, but there is something wrong. You have deleted the ziglings logo. :open_mouth:

**Comment by sterchelen** [comment]
> Thank you for this hint, but there is something wrong. You have deleted the ziglings logo. open_mouth

The main reason I've removed it, is that `LogStep` struct was removed from zig's Build system. In other words, now there is no easy way to show the ziglings header only for the verify_all |  named_chain steps.

I see two options:
1. We show the ziglings header every time we run the zig build command, so no `dependOn` for the header step.
2. We create a custom step to show the header as before. Though, personally I think it's too much complexity added for just a header shown on stdout.

Hope I was clear 😁

**Comment by chrboesch** [comment]
The problem is bigger and requires a general rebuild of the build system: https://github.com/ratfactor/ziglings/issues/202

**Comment by sterchelen** [comment]
> The problem is bigger and requires a general rebuild of the build system: #202

@chrboesch Happy to participate 👍🏼

**Comment by chrboesch** [comment]
@sterchelen You are welcome! :smile:

**Comment by chrboesch** [comment]
Logo problem solved so far, but the main problem with asynchrounus tasks is still there: https://github.com/ratfactor/ziglings/pull/203

**Comment by chrboesch** [comment]
> @chrboesch it seems you did the job... closing then.

No, I didn't. This is only a workaround that Ziglings can used manually. A real solution must work as before. What I did ist some experiments, but there are some bugs in the build system, so I opened an issue yesterday. 

The idea for a sustainable solution is to use the arguments in the build to select whether to compile all tasks one by one, and then re-run the build system one step at a time. In principal it works. I tested yesterday.

**Comment by chrboesch** [comment]
@sterchelen Let's diskuss further here: https://github.com/ratfactor/ziglings/issues/202

**Pull request closed without merging**
