### PR TITLE
Replacing Python-Tools with Zig-Tools

### PR DESCRIPTION
**Pull request by chrboesch**
- [x] check-exercises.py
- [x] update-patches.py

updates https://github.com/ratfactor/ziglings/issues/252

### CODE REVIEW

**Comment by chrboesch** [comment]
> Was it really necessary to reimplement the tools? IMHO Python is perfectly fine in this case, and there is no need to reimplement everything in Zig.

Ziglings has the goal of learning Zig. That's why it's always good to program something in Zig instead of Python. 

> By the way: why use the old diff context instead of the new unified context?

I find it clearer, but it can be easily customized by changing the "-c" parameter to "-u".

Apart from that, the case that an exercise is badly formatted will not occur very often anyway. I already had difficulties to recreate this, because it is automatically formatted when I save.

**Comment by chrboesch** [comment]
@perillo I have a question about the program 'update-patches.py': The program creates the "healed" programs from the exercises and the patches and then creates new patches from the comparison of the "broken" exercises and the "healed" ones. The newly created patches logically look the same as the old ones, since the sources have not changed. So what is the point of this program?

**Comment by perillo** [comment]
> @perillo I have a question about the program 'update-patches.py': The program creates the "healed" programs from the exercises and the patches and then creates new patches from the comparison of the "broken" exercises and the "healed" ones. The newly created patches logically look the same as the old ones, since the sources have not changed. So what is the point of this program?

The  first point it to ensure that all the patch use the same format.  Before, there were 2-3 patches using the unified format.

The second point is to update the context line numbers. They were not exact, because some doc-comments have been updated. The patch command was still able to apply the patch, so it was not a serious problem (probably).

**Comment by chrboesch** [comment]
> because some doc-comments have been updated.

Thanks, that makes sense.

**Comment by chrboesch** [comment]
> By the way: why use the old diff context instead of the new unified context?

When you run `diff -c old_file new_file` you can see why it is clearer (in my opinion). The problem is, the call from a subroutine 'hides' the colors. But, for formatting you can better estimate what the result should be.

**Comment by chrboesch** [comment]
@perillo There seems to be a problem with windows again that we didn't have before.

**Comment by chrboesch** [comment]
Inserted a loop into the formatting tests. Hopefully the next time it freezes we can see on which exercise. https://github.com/ratfactor/ziglings/pull/257

**Comment by perillo** [comment]
> @perillo There seems to be a problem with windows again that we didn't have before.

I suspect the cause is the upgrade to actions/checkout@v3.  It uses Node 16, while goto-bus-stop/setup-zig@v2 probably use the deprecated Node 12.

**Comment by chrboesch** [comment]
> I suspect the cause is the upgrade to actions/checkout@v3. It uses Node 16, while goto-bus-stop/setup-zig@v2 probably use the deprecated Node 12.

I just switched it back to v2.

**Pull request merged**
