### PR TITLE
Added new flag 'run_test' to support test steps for test exercises

### PR DESCRIPTION
**Pull request by chrboesch**
Also created a simple exercise '102_testing' to test the new flag. After the new build system is ready, we skip the exercise in the flow to finish the actual testing exercise.
Regards: https://github.com/ratfactor/ziglings/issues/277

### CODE REVIEW

**Comment by perillo** [comment]
I think you should add full support for testing, instead of first add a new `Exercisercise

> Also created a simple exercise '102_testing' to test the new flag. After the new build system is ready, we skip the exercise in the flow to finish the actual testing exercise. Regards: #277

I think you should add full support for testing, instead of first adding a new `Exercise` field.

**Comment by chrboesch** [comment]
> I think you should add full support for testing, instead of first adding a new Exercise field.

But why, we do not build productivity software, but just for learning purpose?

**Comment by perillo** [comment]
> > I think you should add full support for testing, instead of first adding a new Exercise field.
> 
> But why, we do not build productivity software, but just for learning purpose?

I think there is some misunderstanding here.

What I mean is that you should add a new field for testing an exercise (instead of running it) **and** update the code in `ZiglingStep` to actually spawn `zig test exercise` instead of `zig build-exe exercise`

**Comment by chrboesch** [comment]
> What I mean is that you should add a new field for testing an exercise (instead of running it) and update the code in ZiglingStep to actually spawn zig test exercise instead of zig build-exe exercise

Agree.

**Comment by chrboesch** [comment]
Closes: https://github.com/ratfactor/ziglings/issues/277

**Pull request merged**
