### PR TITLE
Fix deadlock on Windows

### PR DESCRIPTION
**Pull request by perillo**
Let me know if you find some problems.

With the additional commits everything seems ok to me.

The unit test jobs use the cache filled by the eowyn jobs; not sure if this is the correct thing to do but it helps reduce the running time.

UPDATE: there was an error in https://github.com/ratfactor/ziglings/actions/runs/4839360264/jobs/8624337146.

### CODE REVIEW

**Comment by perillo** [comment]
It seems it work.

@chrboesch I plan to add a new commit to remove the custom check for `zig fmt`, since it only adds more unnecessary output.
Also, what was the reason for adding
```sh
# Which version we have?
echo "I am in version 23.4.25.1, let's try our magic power."
```
?

**Comment by perillo** [comment]
@chrboesch  There is also an additional small issue: the patch command generate a lot of output.  I will need to add the `-s` flag.

**Comment by chrboesch** [comment]
> Also, what was the reason for adding
After merging, the Github actions must be deployed. But when failed tests restart, you can't see whether it was the deployed version or not. Because sometimes the deployment fails. I just wanted to see which version was in the test.

**Comment by chrboesch** [comment]
>Let me know if you find some problems.

Unfortunately it seems so: https://github.com/ratfactor/ziglings/actions/runs/4840737330/jobs/8626578024

**Comment by perillo** [comment]
> > Let me know if you find some problems.
> 
> Unfortunately it seems so: https://github.com/ratfactor/ziglings/actions/runs/4840737330/jobs/8626578024

I will try some additional tests on my clone of ziglings

**Comment by perillo** [comment]
It works for me: https://github.com/perillo/ziglings/actions/runs/4843599283/jobs/8631322888.
However I'm not sure if it is using a cache from a previous run.

If there is a failure in another PR, I will add the `--verbose` and `-fsummary` options to `zig build test`.

**Comment by chrboesch** [comment]
> It works for me

If I restart the tests here, it would probably also work. Sometimes like this, sometimes like that. :neutral_face:

**Pull request merged**
