### PR TITLE
Nitpicks: typos, grammar and using while-loop continue expression

### PR DESCRIPTION
**Pull request by Seanny123**

### CODE REVIEW

**Comment by chrboesch** [comment]
Thank you for correcting the typo and grammar in Exercise 093. Changes in exercise 076 are not necessary, as clarity would be lost. I know that you can do the loop in at least 3 different ways. But this is about understanding the 'sentinels', not the loops. :wink:

**Comment by Seanny123** [comment]
> Changes in exercise 076 are not necessary

I've dropped that commit

**Comment by chrboesch** [comment]
@Seanny123 You also have to change build.zig, line 474.

**Comment by chrboesch** [comment]
Thanks!

**Pull request merged**
