### PR TITLE
Updating build.zig to support new API change.

### PR DESCRIPTION
**Pull request by DameonSmith**
I updated zig today and the addExecutable API appears to have changed with it. I was able to get the build to run again with this change.

### CODE REVIEW

**Comment by chrboesch** [comment]
I can't find any mistake.

**Comment by chrboesch** [comment]
> ...and the addExecutable API appears to have changed with it. 

If you compare the zig versions, you can see that there were no changes in this function:

https://ziglang.org/documentation/0.10.1/std/src/build.zig.html#L277

https://ziglang.org/documentation/master/std/src/build.zig.html#L384

**Comment by DameonSmith** [comment]
It's in this commit that was merged into main 2 days ago:
https://github.com/ziglang/zig/commit/efa25e7d5bca63e83f6a653058c05dacc771d19e#diff-355d0d5a29153bf7f7f73e8e64f0b467b26b2c37e824dcc47e872038a58ce855R436

New function definition is on like 436 of std/Build.zig

There's quite a few examples of the new config formatting in there. I'm just running the version of zig built by MacOS Brew. `0.11.0-dev.1540+304420b99`

**Comment by boberhaus** [comment]
+1

PR calls it out explicitly: https://github.com/ziglang/zig/pull/14498

benoberhaus@Bens-MBP ziglings % zig version
0.11.0-dev.1557+03cdb4fb5
benoberhaus@Bens-MBP ziglings % zig build
/Users/benoberhaus/Desktop/Coding/ziglings/build.zig:567:29: error: member function expected 1 argument(s), found 2
        const build_step = b.addExecutable(base_name, file_path);
                           ~^~~~~~~~~~~~~~
/Users/benoberhaus/Desktop/Coding/zig/lib/std/Build.zig:436:5: note: function declared here
pub fn addExecutable(b: *Build, options: ExecutableOptions) *CompileStep {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    runBuild__anon_6059: /Users/benoberhaus/Desktop/Coding/zig/lib/std/Build.zig:1525:27
    usage__anon_4896: /Users/benoberhaus/Desktop/Coding/zig/lib/build_runner.zig:239:20
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

**Comment by chrboesch** [comment]
We are sorry but since they release new dev versions every few days, we can not make a new ziglings version in the same frequency. There are a lot of testing to make everything stable. The zig foundation is growing as sponsorship has increased, and now they have more fulltime devolopers. This means that the frequency of new versions will also increase, which we very much welcome. But we do not have the possibility to keep up with the pace if the quality is not to suffer. However, since ziglings is primarily for learning and understanding the zig language, we need to think about what to do. Maybe it's time to switch to the stable dev version of zig.

**Review by chrboesch — COMMENTED** [review]
build number added

**Pull request merged**
