### PR TITLE
Added a zig version test

### PR DESCRIPTION
**Pull request by Joefish**

### CODE REVIEW

**Comment by Joefish** [comment]
[I was stuck at exercise 06 for quite a bit](https://github.com/ratfactor/ziglings/pull/3#issuecomment-776914166), what could have been solved with a version check like this one.
My bash knowledge is quite limited, so I'm sure there are better ways to compare version strings.

**Comment by SpexGuy** [comment]
This change (requiring `{s}`) was made within the 0.8.0 development cycle (and within the last few days), so versions of the standard library which do not use `{s}` will also report 0.8.0 as their version.  While zig does have methods for checking the more specific version number, they are based on the git commit hash, so you can't easily check for a range.  While I agree in theory that having a version check would be good, I don't think it can be implemented in a way that is useful.

It seems like the way forward here is to fix the exercises that still use `{}`, so master works (since that's what the instructions say to download).  Hosting a separate branch/tag of this repo for 0.7.1 (the last stable version of Zig) with a full version check would be reasonable, but would be more stuff to maintain in general, so might not be worth it.

**Comment by SpexGuy** [comment]
Ah, actually strike that, zig versions now do contain a monotonic commit number.
They are formatted as
`0.8.0-dev.<commits since 0.7.1>+<commit hash>`.
So if we can determine a minimum value for that first number, we can actually do this check.

**Comment by Joefish** [comment]
I tried bisecting it, but after hours of long link times and broken commits I gave up.
I guess it comes down to how you guys want to handle language/std changes.
- stick to a stable release
- stick to latest master
- hunt down commit hashes to compare against

To be honest, the more I think about it the less appealing the last option gets.
So, in my opinion, scrap my PR, update README to download/compile master or a stable release, update exercises accordingly.

**Comment by SpexGuy** [comment]
I have `0.8.0-dev.1065+...`, which allows `{s}` but also allows `{}` and interprets it as `{*}`.  Since the ziglings don't use `{*}` I think that's a safe minimum.

**Comment by ratfactor** [comment]
@Joefish This is a GREAT idea! Nothing is more frustrating that failing a programming exercise because of the tooling itself. (Thanks for figuring it out and sorry for the false errors.)

I'll review this ASAP!

**Comment by Joefish** [comment]
I added a commit version check like SpexGuy proposed in the latest commit.

**Comment by ratfactor** [comment]
@Joefish Excellent. The more I think about it, though, how about we check if _any_ part of the version is less than our minimum?  Then we can loop over the version parts and reject if we hit any "less than" conditions.

Using a regex to get the version parts might be beneficial since we could then handle the possibility of a version format we don't recognize as well.

Maybe something like this:

```bash
zig_cmd=zig
zig_minimum_version="0 8 0 1065"
zig_version=$($zig_cmd version)

if [[ "$zig_version" =~ ([0-9]+)\.([0-9]+)\.([0-9]+)-dev\.([0-9]+) ]]
then
    match_idx=1 # regex matches start at index 1

    for v in $zig_minimum_version
    do
        if [[ ${BASH_REMATCH[$match_idx]} -lt $v ]]
        then
            echo "Ye Zig is too old and must be put to the sword."
            exit 1
        fi
        match_idx=$((match_idx+1))
    done
else
    echo "Sorry, Zig version number '${zig_version}' is not in the expected format for a current development build."
    exit 1
fi
```

What do you think? (Replacing the silly message with the one you wrote, of course.)

BTW: I like storing the target version number in an array just fine, but I only know how to loop over a space-separated list. :laughing: 

It also occurs to me that we could check for an error returned by `ig_version=$($zig_cmd version)` (mostly likely because it doesn't exist or `$PATH` has not been set) and warn about that, too.   Would you be okay with adding that check as well while you're in there?

Thanks a bunch for your work on this.

Also, thanks @SpexGuy for the build number tip. That's going to make this possible!

_Pondering: What I'm likely to do is update both the README and the minimum version in the script whenever I update the Zig executable I'm testing Ziglings with...which reminds me, I ought to figure out how to automate testing Ziglings... :thinking:_

**Comment by Joefish** [comment]
Your version is way better. Totally forgot that there's regex in bash..
I added a check for a failed `zig version` and pipe the error message to null.

**Comment by ratfactor** [comment]
@Joefish Looks like we're getting a Zig build system script in PR #8 , but I'll be sure to merge your work first since it deserves to exist. I really appreciate it!  I'm hoping to get caught up on everything this weekend. :smile:

**Comment by ratfactor** [comment]
@Joefish Thanks again, works great!

**Comment by Joefish** [comment]
I'm glad it is of help. But PR #8 is the way forward, especially with testing in mind.
I didn't expect SpexGuy be so fast, basically rewriting the shell script to a zig build file.
Really cool to see it being improved so fast

**Comment by ratfactor** [comment]
Ha ha, no kidding. Not in my wildest imaginings did I think that shell script would be gone so soon!

**Pull request merged**
