### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by perillo**
In this branch I plan to improve the CI

  - [x] Add a new github workflow dedicated to CI
  - [x] Add a job checking compatibility with older Zig versions
         TODO: document why the `ci/compat.sh` script needs to use `grep`.
  - [x] Ensure all .zig files have conforming code formatting 
         Now the Eowyn workflow will ensure it.
         See also #222.
         .
         I wanted to add a quote like "May the compiler have mercy upon us." in bd777dc.
         Something like "follow the orthodoxy" but I'm not very good at it.
         .
         Most of the time, the code formatting was not conforming in order to keep comments aligned.
         I think this causes only problems (see Go, when a simple change may cause a huge code reformatting),
         and using `zig fmt: off` is probably a very bad idea for newcomers.
  - [x] Make the patch files consistent
    See also #244.
    .
    It was interesting that the headers of the two patches in unified format was
    ```
    --- exercises/080_anonymous_structs.zig
    +++ answers/080_anonymous_structs.zig
    ```
    .
    Is the old `answers` directory used when creating a new exercise?

### CODE REVIEW

**Comment by perillo** [comment]
The build runner exits with exit code 1, ignoring the child exit code.  Zig 0.6.0 works *correctly*, instead.

**Comment by chrboesch** [comment]
But the question is, back to which version and for what?

**Comment by perillo** [comment]
> But the question is, back to which version and for what?

In the job I used Zig 0.6.0, 0.7.0, 0.8.0, 0.9.0 and 0.10.0.  That is, all the old stable releases.
I have updated the bash script, and now it works.

The problem, however, is that a new version of the Zig compiler has been released, and it broke the `Eowyn` workflow.

I wlll update the `build.zig` file to the new API.

**Comment by perillo** [comment]
@chrboesch Can you run the github action again?  Thanks.

**Comment by chrboesch** [comment]
deprecated; use std.Build.installArtifact

**Comment by chrboesch** [comment]
@perillo Maybe you should update your branch, before continuing.

**Comment by perillo** [comment]
> @perillo Maybe you should update your branch, before continuing.

You are right.  I assumed that when running the action my branch would be rebased to `main` automatically.  Sorry for the noise.

**Comment by chrboesch** [comment]
Everything is fine, thank you!

**Comment by perillo** [comment]
> Yeah, thank you for all the great work, @perillo !

It was fun.  Ziglings uses the Build system in a creative way, so I learned a lot about how it works.

But there are still several changes in my TODO file.

**Pull request merged**
